// packages/react-ui/src/components/PlayControl/PlayControl.tsx
import './PlayControl.scss';

import { Player } from '@darkvi/core';
import { useContext, useEffect, useState } from 'react';

import { PlayerContext } from '@/components';
import { PauseIcon, PlayIcon } from '@/icons';

function PlayControl() {
  const player = useContext<Player | null>(PlayerContext);
  const [paused, setPaused] = useState<boolean>(true);

  useEffect(() => {
    player?.on('pause', onPaused);
    player?.on('playing', onPlaying);

    return () => {
      player?.off('pause', onPaused);
      player?.off('playing', onPlaying);
    };
  });

  const onPaused = () => setPaused(true);
  const onPlaying = () => setPaused(false);

  const togglePlay = () => {
    player?.togglePlay();
  };

  return (
    <div className="drk-vi-play" onClick={togglePlay}>
      {paused ? (
        <PlayIcon className="drk-vi-play__icon" width="22" height="22" />
      ) : (
        <PauseIcon className="drk-vi-play__icon" width="22" height="22" />
      )}
    </div>
  );
}

export default PlayControl;

// packages/ui/src/components/play-control/play-control.component.ts
import { Player } from '@darkvi/core';

import { Component } from '../../decorators';
import { PauseIcon, PlayIcon } from '../../icons';
import { getNativeEl, getPlayerInstanceFromControl } from '../../utils';
import $styles from './play-control.styles.scss?inline';

@Component({
  selector: 'drk-vi-play',
  template: ' <div data-container class="drk-vi-play"></div> ',
  styles: $styles,
})
export class PlayControlComponent extends HTMLElement {
  private _containerEl!: HTMLDivElement;

  private get _player(): Player {
    return getPlayerInstanceFromControl(this);
  }

  connectedCallback() {
    this._containerEl = getNativeEl<HTMLDivElement>(this, '[data-container]')!;
    this.addEventListener('click', this.onControlClick);

    requestAnimationFrame(() => {
      this.renderControl(!this._player.$mediaEl.paused);
      this._player.on('playing', this.onPlaying);
      this._player.on('pause', this.onPause);
    });
  }

  disconnectedCallback() {
    this.removeEventListener('click', this.onControlClick);
    this._player.off('playing', this.onPlaying);
    this._player.off('pause', this.onPause);
  }

  private onControlClick = () => this._player.togglePlay();
  private onPlaying = () => this.renderControl(true);
  private onPause = () => this.renderControl(false);

  private renderControl = (isPlaying: boolean) => {
    const options = {
      className: 'drk-vi-play__icon',
      width: '22',
      height: '22',
    };
    
    this._containerEl.innerHTML = isPlaying ? PauseIcon(options) : PlayIcon(options);
  };
}
