// packages/ui/src/components/fullscreen-control/fullscreen-control.component.tsx
import { Player } from '@darkvi/core';

import { BaseComponent, CustomElement, withTooltip } from '../../core';
import { ExitFullscreenIcon, FullscreenIcon } from '../../icons';
import { getPlayerInstanceFromControl } from '../../utils';
import $styles from './fullscreen-control.styles.scss?inline';

const FULLSCREEN_EVENTS = ['fullscreenchange', 'mozfullscreenchange', 'webkitfullscreenchange'];

@CustomElement('drk-vi-fullscreen')
@withTooltip('[data-tooltip="tooltip"]')
export class FullscreenControlComponent extends BaseComponent {
  $$styles = $styles;

  get isFullscreen(): boolean {
    return Boolean(this.player?.isFullscreen);
  }

  private get player(): Player {
    return getPlayerInstanceFromControl(this);
  }

  onMount() {
    FULLSCREEN_EVENTS.forEach((event: string) => {
      this.player.$containerEl.addEventListener(event, this.onFullscreenChanged);
    });
  }

  onDestroy() {
    FULLSCREEN_EVENTS.forEach((event: string) => {
      this.player.$containerEl.removeEventListener(event, this.onFullscreenChanged);
    });
  }

  render(): Node {
    const Icon = this.isFullscreen ? ExitFullscreenIcon : FullscreenIcon;

    return (
      <div class="drk-vi-fullscreen" onclick={this.onControlClick}>
        <Icon className="drk-vi-fullscreen__icon" width="22" height="22" />

        <span data-tooltip="tooltip" role="tooltip" class="drk-vi-tooltip">
          {this.isFullscreen ? 'Exit fullscreen' : 'Enter fullscreen'}
        </span>
      </div>
    );
  }

  private onControlClick = () => {
    this.isFullscreen ? this.player.fromFullScreen() : this.player.toFullScreen();
  };

  private onFullscreenChanged = () => {
    this.$$detectChanges();
  };
}

declare global {
  interface HTMLElementTagNameMap {
    'drk-vi-fullscreen': FullscreenControlComponent;
  }

  interface IntrinsicElements {
    ['drk-vi-fullscreen']: FullscreenControlComponent;
  }
}

// packages/ui/src/components/fullscreen-control/fullscreen-control.component.ts
import { Player } from '@darkvi/core';

import { Component } from '../../decorators';
import { ExitFullscreenIcon, FullscreenIcon } from '../../icons';
import { getNativeEl, getPlayerInstanceFromControl } from '../../utils';
import $styles from './fullscreen-control.styles.scss?inline';

const FullscreenChangeEvents = [
  'fullscreenchange',
  'mozfullscreenchange',
  'webkitfullscreenchange',
];

@Component({
  selector: 'drk-vi-fullscreen',
  template: ' <div data-container class="drk-vi-fullscreen"></div> ',
  styles: $styles,
})
export class FullscreenControlComponent extends HTMLElement {
  private _containerEl!: HTMLDivElement;

  private get _player(): Player {
    return getPlayerInstanceFromControl(this);
  }

  connectedCallback() {
    this._containerEl = getNativeEl<HTMLDivElement>(this, '[data-container]')!;
    this.addEventListener('click', this.onControlClick);

    requestAnimationFrame(() => {
      this.renderControl();

      FullscreenChangeEvents.forEach((event: string) => {
        this._player.$containerEl.addEventListener(event, this.renderControl);
      });
    });
  }

  disconnectedCallback() {
    this.removeEventListener('click', this.onControlClick);

    FullscreenChangeEvents.forEach((event: string) => {
      this._player.$containerEl.removeEventListener(event, this.renderControl);
    });
  }

  private onControlClick = () => {
    this._player.isFullscreen ? this._player.fromFullScreen() : this._player.toFullScreen();
  };

  private renderControl = () => {
    const options = {
      className: 'drk-vi-fullscreen__icon',
      width: '22',
      height: '22',
    };

    this._containerEl.innerHTML = this._player.isFullscreen
      ? ExitFullscreenIcon(options)
      : FullscreenIcon(options);
  };
}

declare global {
  interface HTMLElementTagNameMap {
    'drk-vi-fullscreen': FullscreenControlComponent;
  }
}
