// packages/react-ui/src/components/VolumeControl/VolumeControl.tsx
import './VolumeControl.scss';

import { Player } from '@darkvi/core';
import clsx from 'clsx';
import { useContext, useEffect, useState } from 'react';
import Slider from 'react-slider';

import { PlayerContext } from '@/components';
import { MutedIcon, SoundIcon } from '@/icons';

function VolumeControl() {
  const player = useContext<Player | null>(PlayerContext);
  const [muted, setMuted] = useState<boolean>(Boolean(player?.$mediaEl.muted));
  const [volume, setVolume] = useState<number>(player?.$mediaEl.volume ?? 0);

  useEffect(() => {
    if (player) {
      player.on('volumechange', onVolumeChange);
      player.on('playing', onVolumeChange);
    }

    return () => {
      player.off('volumechange', onVolumeChange);
      player.off('playing', onVolumeChange);
    };
  });

  const onVolumeChange = () => {
    if (!player) return;
    setVolume(player.$mediaEl.volume);
    setMuted(player.$mediaEl.muted);
  };

  const toggleMute = () => {
    if (!player) return;
    player.$mediaEl.muted = !player.$mediaEl.muted;
  };

  const changeVolume = (value: number) => {
    if (!player) return;

    player.$mediaEl.volume = value;
    if (muted) toggleMute();
  };

  return (
    <div className={clsx('drk-vi-volume', muted && 'drk-vi-volume--muted')}>
      <div className="drk-vi-volume__button" onClick={toggleMute}>
        {muted ? (
          <MutedIcon className="drk-vi-volume__icon" height="22" width="22" />
        ) : (
          <SoundIcon className="drk-vi-volume__icon" height="22" width="22" />
        )}
      </div>

      <Slider
        className="drk-vi-volume__level"
        trackClassName="drk-vi-volume__level_track"
        thumbClassName="drk-vi-volume__level_thumb"
        thumbActiveClassName="drk-vi-volume__level_thumb--active"
        min={0}
        max={1}
        step={0.1}
        value={volume || 0}
        onChange={changeVolume}
      />
    </div>
  );
}

export default VolumeControl;

// packages/ui/src/components/volume-control/volume-control.component.ts
import { Player } from '@darkvi/core';

import { Component } from '../../decorators';
import { MutedIcon, SoundIcon } from '../../icons';
import { getNativeEl, getPlayerInstanceFromControl } from '../../utils';
import $styles from './volume-control.styles.scss?inline';

@Component({
  selector: 'drk-vi-volume',
  template: `
    <div data-container class="drk-vi-volume">
      <div data-button class="drk-vi-volume__button"></div>

      <input
        data-slider
        class="drk-vi-volume__slider drk-vi-slider"
        role="slider"
        type="range"
        min="0"
        max="1"
        value="0"
        step="0.01"
      />
    </div>
  `,
  styles: $styles,
})
export class VolumeControlComponent extends HTMLElement {
  protected _containerEl!: HTMLDivElement;
  protected _sliderEl!: HTMLInputElement;
  protected _buttonEl!: HTMLDivElement;

  private get _player(): Player {
    return getPlayerInstanceFromControl(this);
  }

  connectedCallback() {
    this._containerEl = getNativeEl<HTMLDivElement>(this, '[data-container]')!;
    this._sliderEl = getNativeEl<HTMLInputElement>(this, '[data-slider]')!;
    this._buttonEl = getNativeEl<HTMLDivElement>(this, '[data-button]')!;

    requestAnimationFrame(() => {
      this.onVolumeUpdate();
      this.renderButton(this._player.$mediaEl.muted);

      this._player.on('volumechange', this.onVolumeUpdate);
      this._sliderEl.addEventListener('input', this.setNewVolume);
      this._buttonEl.addEventListener('click', this.toggleMute);
    });
  }

  disconnectedCallback() {
    this._player.off('volumechange', this.onVolumeUpdate);
    this._sliderEl.removeEventListener('input', this.setNewVolume);
    this._buttonEl.removeEventListener('click', this.toggleMute);
  }

  private onVolumeUpdate = () => {
    const { volume, muted } = this._player.$mediaEl;

    this._sliderEl.value = volume.toString();
    this.rePaintSliderEl(volume * 100);

    muted
      ? this._containerEl.classList.add('drk-vi-volume--muted')
      : this._containerEl.classList.remove('drk-vi-volume--muted');
  };

  private setNewVolume = (event: Event) => {
    const value = Number((event.target as HTMLInputElement).value) ?? 0;
    this._player.$mediaEl.volume = value;
    this.rePaintSliderEl(value * 100);

    if (this._player.$mediaEl.muted) this.toggleMute();
  };

  private toggleMute = () => {
    this._player.$mediaEl.muted = !this._player.$mediaEl.muted;

    requestAnimationFrame(() => {
      this.renderButton(this._player.$mediaEl.muted);
    });
  };

  private renderButton = (isMuted: boolean) => {
    const options = {
      className: 'drk-vi-volume__icon',
      width: '22',
      height: '22',
    };

    this._buttonEl.innerHTML = isMuted ? MutedIcon(options) : SoundIcon(options);
  };

  private rePaintSliderEl = (progress: number) => {
    this._sliderEl.style.setProperty('--value', `${progress}%`);
  };
}

declare global {
  interface HTMLElementTagNameMap {
    'drk-vi-volume': VolumeControlComponent;
  }
}
