// packages/react-ui/src/components/Poster/Poster.tsx
import './Poster.scss';

import { Player } from '@darkvi/core';
import { useContext, useEffect, useState } from 'react';

import { PlayerContext } from '@/components';
import { PlayIcon } from '@/icons';

interface Props {
  src?: string;
  waitPlaying?: boolean;
}

function Poster({ src, waitPlaying = false }: Props) {
  const { $mediaEl, once } = useContext<Player | null>(PlayerContext);
  const [isVisible, setIsVisible] = useState<boolean>(true);

  useEffect(() => {
    setIsVisible(true);
  }, [src]);

  const onPosterClick = async () => {
    await $mediaEl.play();
    waitPlaying ? once('playing', () => setIsVisible(false)) : setIsVisible(false);
  };

  return (
    <>
      {isVisible ? (
        <div className="drk-vi-poster" onClick={onPosterClick}>
          <img src={src} alt="drk-vi-poster" className="drk-vi-poster__image" />
          <PlayIcon className="drk-vi-poster__icon" />
        </div>
      ) : null}
    </>
  );
}

export default Poster;

// packages/ui/src/components/poster/poster.component.ts
import { Player } from '@darkvi/core';

import { PlayIcon } from '@/icons';
import { getPlayerInstanceFromControl } from '@/utils';

import { Component } from '../../decorators';
import $styles from './poster.styles.scss?inline';

@Component({
  selector: 'drk-vi-poster',
  template: `
    <div class="drk-vi-poster">
      <slot></slot>

      <div class="drk-vi-poster__icon">
        <slot name="icon">${PlayIcon()}</slot>
      </div>
    </div>
  `,
  styles: $styles,
})
export class PosterComponent extends HTMLElement {
  connectedCallback() {
    this.addEventListener('click', this.onPosterClick);
  }

  disconnectedCallback() {
    this.removeEventListener('click', this.onPosterClick);
  }

  private onPosterClick = async () => {
    const player = getPlayerInstanceFromControl(this) as Player | null;

    if (!player) return;

    await player.$mediaEl.play();

    if (this.getAttribute('waitPlaying')) {
      player.once('playing', this.hidePoster);
    } else {
      this.hidePoster();
    }
  };

  private hidePoster = () => {
    this.hidden = true;
  };
}
